name: Run Tests

on:
  push:

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.4.2]
        os: [ubuntu-latest, macos-latest]
        extensions:
          - none, mbstring, curl, dom, xml, xmlwriter, tokenizer, ctype
          - sqlsrv

    name: P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.extensions }}

    steps:
      - name: Check LC_ALL
        run: echo "$LC_ALL"
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: short_open_tag=on, sqlsrv.SetLocaleInfo=0, pdo_sqlsrv.set_locale_info=0
          coverage: none
          
      - name: Check PHP Configuration
        run: |
          echo "LC_ALL environment: $LC_ALL"
          php -i | grep -E "(sqlsrv|pdo_sqlsrv)" || echo "No sqlsrv configuration found"
          php -m | grep -E "(sqlsrv|pdo_sqlsrv)" || echo "No sqlsrv extensions found"
          php -r "echo 'sqlsrv.SetLocaleInfo: ' . ini_get('sqlsrv.SetLocaleInfo') . PHP_EOL;"
          php -r "echo 'pdo_sqlsrv.set_locale_info: ' . ini_get('pdo_sqlsrv.set_locale_info') . PHP_EOL;"
          php -r "echo 'Current locale: ' . setlocale(LC_ALL, 0) . PHP_EOL;"
        
      - name: Install dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer update --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/phpunit
