name: Run Tests

on:
  push:

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.4.3]
        os: [macos-latest]
        extensions:
          - none, mbstring, curl, dom, xml, xmlwriter, tokenizer, ctype
          - sqlsrv-5.11.0

    name: P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.extensions }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libs
        run: brew install unixodbc-dev

      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: short_open_tag=on
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer update --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/phpunit
